### ISSUE TITLE
Fatal error: unction parseProperties() on null in /core/model/modx/modelement.class.php:524 

### ISSUE THREAD

**Issue by Andy-Post** [BobRay/UpgradeMODX#50]
Hi,
I always get this error after start upgrading with upgradeModx:
`Fatal error: Uncaught Error: Call to a member function parseProperties() on null in 
/var/www/vhosts/domain.tld/httpsdocs/core/model/modx/modelement.class.php:524 
Stack trace: 
#0 /var/www/vhosts/domain.tld/httpsdocs/core/model/modx/modx.class.php(1606): modElement->getProperties() 
#1 /var/www/vhosts/domain.tld/httpsdocs/core/model/modx/modx.class.php(538): modX->invokeEvent('OnMODXInit', Array) 
#2 /var/www/vhosts/domain.tld/httpsdocs/setup/includes/modinstall.class.php(491): modX->initialize('mgr') 
#3 /var/www/vhosts/domain.tld/httpsdocs/setup/includes/modinstall.class.php(149): modInstall->_modx(Array) 
#4 /var/www/vhosts/domain.tld/httpsdocs/setup/includes/test/modinstalltest.class.php(306): modInstall->getConnection() 
#5 /var/www/vhosts/domain.tld/httpsdocs/setup/includes/test/modinstalltest.class.php(42): modInstallTest->_checkDatabase() 
#6 /var/www/vhosts/domain.tld/httpsdocs/setup/includes/modinstall.class.php(228): modInstallTest->run(1) 
#7 /var/www/vhosts/domain.tld/httpsdocs/setu in /var/www/vhosts/domain.tld/httpsdocs/core/model/modx/modelement.class.php on line 524`

Posted this in https://forums.modx.com/thread/104330/upgrademodx-fatal-error-uncaught-error-call-to-a-member-function-parseproperties-on-null-in-modelement-class-php-524#dis-post-561185 and slack-chanel also - wasn't shure where to place this correct.

**Comment by BobRay** [comment]
That appears to be an error in Setup, not UpgradeMODX. UGM just puts the files in place and launches setup.

**Comment by sebastian-marinescu** [comment]
Hi @Andy-Post, did you figure it out?
